pipeline:
  build-and-push:
    image: redpencil/plugin-docker-buildx:add-remote-builders
    settings:
      platforms: linux/amd64,linux/arm64
      repo: "redpencil/${CI_REPO_NAME%%-docker}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
    secrets: [docker_username, docker_password, ssh_key, remote_builders]
    when:
      event: push
      branch: feature/*
